<HTML>
<HEAD>
<meta charset="UTF-8">
<title>catch - </title>
<link rel="stylesheet" href="../style.css">
</HEAD>
<BODY>
<a href="index.html">assertk</a>&nbsp;/&nbsp;<a href="./catch.html">catch</a><br/>
<br/>
<h1>catch</h1>
<a name="assertk$catch(kotlin.Function0((kotlin.Unit)))"></a>
<code><span class="keyword">fun </span><span class="identifier">catch</span><span class="symbol">(</span><span class="identifier" id="assertk$catch(kotlin.Function0((kotlin.Unit)))/f">f</span><span class="symbol">:</span>&nbsp;<span class="symbol">(</span><span class="symbol">)</span>&nbsp;<span class="symbol">-&gt;</span>&nbsp;<a href="https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-unit/index.html"><span class="identifier">Unit</span></a><span class="symbol">)</span><span class="symbol">: </span><a href="https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-throwable/index.html"><span class="identifier">Throwable</span></a><span class="symbol">?</span></code>
<p><strong>Platform and version requirements:</strong> Common</p>
<p>Catches any exceptions thrown in the given lambda and returns it. This is an easy way to assert on expected thrown
exceptions.</p>
<pre><code>val exception = catch { throw Exception("error") }
assertThat(exception).isNotNull().hasMessage("error")
</code></pre>
</BODY>
</HTML>
